### ISSUE TITLE
Error Getting Stats

### ISSUE THREAD

**Issue by zanzertuchi** [715209/nginx-obs-automatic-low-bitrate-switching#25]
Hey there, 

having an issue where I can't seem to get the stats portion working on the app.  

I'm on ubuntu, I can see the stat page (on the box and off), The rtmp source shows up in OBS - everything else but that seems to be working.   

Any thoughts?  I'm stumped :P

**Comment by zanzertuchi** [comment]
[4/11/2020] [11:24:47 PM] [OBS] › ✖  error     [NGINX] Error fetching stats
[4/11/2020] [11:24:47 PM] [OBS] › ✖  error     TypeError: Cannot read property 'live' of undefined 
    at /home/zanzer/noalbs/lib/components/ObsSwitcher.js:224:21
    at Parser.<anonymous> (/home/zanzer/noalbs/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:189:13)
    at SAXParser.onclosetag (/home/zanzer/noalbs/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/home/zanzer/noalbs/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/zanzer/noalbs/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/zanzer/noalbs/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/zanzer/noalbs/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/home/zanzer/noalbs/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/home/zanzer/noalbs/node_modules/xml2js/lib/parser.js:5:59)


This is the error I'm seeing as I start to dig in.

**Comment by 715209** [comment]
Hello Zanzertuchi,

Could you show me your nginx stats page.

**Comment by zanzertuchi** [comment]
Hey! 

I'm just using the default stat stuff that you had in here, I was just trying to get it setup and working before I did any sort of tweaking :D

**Comment by 715209** [comment]
Are you sure your config.json is set up correctly? 

https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/blob/3b262f96fb05954bf7fe1e0d0179fe2fd58918f0/config.json#L14-L18

**Comment by zanzertuchi** [comment]
That's completely on me. 

I should have noticed that I was streaming to /publish/live; even though I changed the config to point to a different app/key.     One of those lack of sleep mistakes.. 

My question now is - I'm taking it that that isn't actually configurable and that you need to keep that app and key to publish / live?  

Sorry for the ping on bad testing on my part.  lol

**Comment by 715209** [comment]
No you can change the app and key. 
You just need to tell NOALBS where to look for the stats by editing it in config.json

**Comment by zanzertuchi** [comment]
Thanks guys.

Totally my dumbass on this one.  Thanks for making this amazing project 👍   - saving me a ton of money, when I need to be saving money. lol
